# Generated by Django 5.2.8 on 2025-11-09 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxgrades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigenInformacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('tipo_ingreso', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importación'), ('masivo', 'Carga masiva')], default='manual', max_length=10)),
                ('encargado', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('validado_formato', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Origen de información',
                'verbose_name_plural': 'Orígenes de información',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mercado', models.CharField(choices=[('CL', 'Chile'), ('US', 'USA'), ('EU', 'Europa')], max_length=4)),
                ('origen_texto', models.CharField(blank=True, max_length=100)),
                ('periodo_comercial', models.DateField()),
                ('instrumento', models.CharField(max_length=120)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('secuencia_evento', models.CharField(blank=True, max_length=60)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dividendo', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('habilitado', models.BooleanField(default=True)),
                ('factor', models.DecimalField(decimal_places=6, default=1, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='taxgrades.origeninformacion')),
            ],
            options={
                'ordering': ['-periodo_comercial', 'instrumento', 'secuencia_evento'],
                'indexes': [models.Index(fields=['periodo_comercial'], name='taxgrades_c_periodo_e1870c_idx'), models.Index(fields=['instrumento'], name='taxgrades_c_instrum_90f8fc_idx'), models.Index(fields=['mercado'], name='taxgrades_c_mercado_810e2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrumento', 'periodo_comercial', 'secuencia_evento'), name='uq_calif_instrumento_periodo_secuencia', violation_error_message='Ya existe una calificación para ese instrumento/periodo/secuencia.')],
            },
        ),
    ]
