# Generated by Django 5.2.8 on 2025-11-09 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxgrades', '0002_origeninformacion_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=30)),
                ('user', models.CharField(blank=True, max_length=120)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxgrades.origeninformacion')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
